# This is a work in progress for a radio interface
# Eric plans to purchase an MGL V16 radio, once in hand 
# development on this feature will continue
RADIO:
  include:
  - screens/virtualvfr_db.yaml
  - HMI_ENCODER_BUTTONS
  module: pyefis.screens.screenbuilder
  title: Radio Screen
  layout:
    rows: 110
    columns: 200
    #draw_grid: true
  instruments:
    - type: value_text
      disabled: DEMO_TESTING_TEXT
      row: 103
      column: 30
      span:
        rows: 6
        columns: 60
      options:
        dbkey: MAVMSG
        font_percent: 0.9
    - type: include,includes/ahrs/virtual_vfr.yaml
      disabled: false
      row: 0
      column: 0
      span:
        rows: 45
        columns: 200
    - type: include,BUTTON_GROUP2
      disabled: BUTTONS
      row: 100
      column: 0
    - type: include,includes/bars/vertical/six_wide_preferences_BAR1-6.yaml
      row: 70
      column: 155
    - type: include,RADIO_VOLUMES
      replace:
        radio_id: 1
      row: 75
      column: 0
      span:
        rows: 23
        columns: 50
    - type: include,RADIO_LISTBOX
      replace:
        radio_id: 1
      row: 75
      column: 51
      span:
        rows: 23
        columns: 148
    - type: include,RADIO_COMBINED_MINIMAL
      replace:
        radio_id: 1 # {radio_id} is replaced anywhere it appears in the included config
                    # Maybe you have two radios COMACTTX{radio_id} -> COMACTTX1
      row: 45
      column: 0
      span:
        rows: 30
        columns: 200



